Hibernate:
    create table app_user (
        id bigint generated by default as identity,
        email varchar(255) unique,
        name varchar(255),
        password varchar(255),
        primary key (id)
    )
Hibernate:
    create table driver (
        available boolean,
        rating float(53),
        id bigint generated by default as identity,
        user_id bigint unique,
        current_location Geometry(Point, 4326),
        primary key (id)
    )
Hibernate:
    create table ride (
        fare float(53),
        created_time timestamp(6),
        driver_id bigint,
        ended_at timestamp(6),
        id bigint generated by default as identity,
        rider_id bigint,
        started_at timestamp(6),
        otp varchar(255),
        payment_method varchar(255) check (payment_method in ('CASH','WALLET')),
        ride_status varchar(255) check (ride_status in ('CONFIRMED','ONGOING','ENDED','CANCELLED')),
        drop_off_location Geometry(Point, 4326),
        pickup_location Geometry(Point, 4326),
        primary key (id)
    )
Hibernate:
    create table rider (
        rating float(53),
        id bigint generated by default as identity,
        user_id bigint unique,
        primary key (id)
    )
Hibernate:
    create table ride_request (
        id bigint generated by default as identity,
        requested_time timestamp(6),
        rider_id bigint,
        payment_method varchar(255) check (payment_method in ('CASH','WALLET')),
        ride_request_status varchar(255) check (ride_request_status in ('PENDING','CONFIRMED','CANCELLED')),
        drop_off_location Geometry(Point, 4326),
        pickup_location Geometry(Point, 4326),
        primary key (id)
    )
Hibernate:
    create table user_roles (
        user_id bigint not null,
        roles varchar(255) check (roles in ('ADMIN','DRIVER','RIDER'))
    )
Hibernate:
    alter table if exists driver
       add constraint FK29a5l15muu6jqd77k1vp91fhw
       foreign key (user_id)
       references app_user
Hibernate:
    alter table if exists ride
       add constraint FKo12dq19jo25foqggvedgvaa0p
       foreign key (driver_id)
       references driver
Hibernate:
    alter table if exists ride
       add constraint FKojie7hvuyn0t49px5hsxt5cr8
       foreign key (rider_id)
       references rider
Hibernate:
    alter table if exists rider
       add constraint FKpciwlqisj1l3dbqsv52bg76kd
       foreign key (user_id)
       references app_user
Hibernate:
    alter table if exists ride_request
       add constraint FKcduxgbjabdg5yolikiws9vn7p
       foreign key (rider_id)
       references rider
Hibernate:
    alter table if exists user_roles
       add constraint FK6fql8djp64yp4q9b3qeyhr82b
       foreign key (user_id)
       references app_user
